source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/wayde191/IHakulaSpecs.git'

platform :ios, '7.1'

# BBQ common dependencies
def commonPods
    pod 'IHakulaInfrastructure', :path => '/Users/CNwwsun/iHakula/IHakulaInfrastructure'
    pod 'IHakulaRequest', :path => '/Users/CNwwsun/iHakula/IHakulaRequest'
    pod 'iHakulaImageView', :path => '/Users/CNwwsun/iHakula/iHakulaImageView'
end

target 'iHakulaImageViewTesting' do
    commonPods
end

target 'iHakulaImageViewTestingTests' do
    commonPods
end

